# Check on http://lint.travis-ci.org/ after modifying! Taken and modified
# from https://github.com/biocore/scikit-bio/blob/master/.travis.yml
sudo: false
language: python
python:
  - "3.4"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib nose scikit-bio=0.2.3 "ipython <4.0.0" tornado jsonschema
  - source activate env_name
  - pip install https://github.com/gregcaporaso/build-iab/archive/master.zip
  - pip install .
  - biab notebook -i book -o ipynb
script:
  # Running through all notebooks takes awhile, so bail if the unit tests fail.
  - nosetests --with-doctest && python runipynbs.py ipynb
