# Check on http://lint.travis-ci.org/ after modifying! Taken and modified
# from https://github.com/biocore/scikit-bio/blob/master/.travis.yml
sudo: false
language: python
python:
  - "3.4"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n iab python=$TRAVIS_PYTHON_VERSION -c https://conda.anaconda.org/biocore --file ci/conda_requirements.txt
  - source activate iab
  - pip install -r ci/pip_requirements.txt
  - pip install . --no-deps
  - pip freeze
  - biab notebook -i book -o ipynb
script:
  # Running through all notebooks takes awhile, so bail if the unit tests fail.
  - nosetests --with-doctest && python runipynbs.py ipynb
