channels:
  - etetoolkit
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - notebook
  - scikit-bio >= 0.5.5, < 0.6.0
  - networkx = 2.3.0
  - ete3
  - ete_toolchain
  - pip:
    - https://github.com/caporaso-lab/An-Introduction-To-Applied-Bioinformatics/archive/master.zip
